[package]
name = "mqtt-messages"
version = "0.1.0"
authors = [
    "Tanks Transfeld <tanks.transfeld@ferrous-systems.com>",
    "Sergio Gasquez <sergio.gasquez@gmail.com>",
]
edition = "2021"

[dependencies]
rgb = "=0.8.36"
